### ISSUE TITLE
Research prior art, and see if there is a repo to fork and get started

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-chatbox#2]
Research previous implementations of similar concept, such as intercom, ...

Getting started: perhaps fork the FOAM reviews repo?

**Comment by oznekenzo** [comment]
Benchmarking
• [Intercom](https://www.intercom.com/)
• [Front](https://frontapp.com/)
• [Freshworks](https://www.freshworks.com/)
Should be noted that it's mostly the UI/UX of the chat pop up that we're looking at with the above offerings

Rough specs
• Pop up version, in-page chat box version
• Minimal design
• Can work in authorization contexts A-C
• Should / can there be context D - comment as anon? @michaelsena 

We'll be using [this](https://github.com/kingofthestack/react-chat-window) OS chat component with much of the same authorization logic used from the Comments component
• [another option](https://github.com/Wolox/react-chat-widget)
