### ISSUE TITLE
Update 3box lib in Chatbox

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-chatbox#24]
The new library removes the need to sync messages on load.  This also requires unimplementing the loading feature that was put in this sprint.

- [ ] Remove loading code
- [ ] Remove blocking screen
- [ ] Add Join button in chat interface (?)
- [ ] Automatically join if user has already signed in

**Comment by michaelsena** [comment]
See if we can pass authentication from the hub app to the plugin so we don't need to authenticate 2x
