### ISSUE TITLE
Create basic component implementation

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-chatbox#3]

**Comment by oznekenzo** [comment]
- [x] fork comments component and integrate OS chat
- [x] chat working with comments thread
- [x] switch to ghost thread
- [x] user profiles render
- [x] add "Commenting as" [instead just showing profile picture]
- [x] authorization contexts A-C (D?) [D is not possible at this time]
- [x] loading animations
- [x] "Join this ghost chat to see messages" message over unjoined ghost thread
- [x] add names
- [x] add time stamp
- [x] emoji picker working
- [x] Chat component W/ & W/O pop up

**Comment by oznekenzo** [comment]
- [x] direct to docs site
- [x] approve in your wallet
