### ISSUE TITLE
Polish and clean up edge cases

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-chatbox#4]

**Comment by oznekenzo** [comment]
- [x] Group messages by sender
- [x] Message styling edge cases
- [x] Can't send until thread joined
- [x] new message notifications & # of users when closed
- [x] Working as chat and popup chat
- [x] sound notification
- [x] show number of users online [not possible at the moment]
- [ ] create profile from join screen
- [x] Clean & refactor
